language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ryebro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryebro/docker-react npm run test

deploy:
  provider: elesticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-047650179555"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_KEY
